### ISSUE TITLE
Do sizes of Content and style have to be the same ?

### ISSUE THREAD

**Issue by Nerdyvedi** [zhijieW94/ETNet#1]
Is it necessary to have the sizes of content and style as the same size, I tested your model with input content size of 256x256 and style image of 1312x564 , The results were not good. 

Could we not use this model for arbitrary size inputs ?

PS : Thank you for such a wonderful work.

**Comment by zhijieW94** [comment]
Thank you for your interests in our work.

As an arbitrary style transfer network, our model can take images with arbitrary sizes. But as you can see, it might fail in some cases. And even if the input content and style images share the same size, we can not always guarantee a successful style transfer. 

But when input images have similar sizes (like 512x512 or 768x768), our model is likely to produce more visual pleasing results.

**Comment by Nerdyvedi** [comment]
Yeah, I noticed it does not work that great when applied to arbitrary sizes. I think using PIL resize function is better, tf's resize function does not well from what I have experience.
