### ISSUE TITLE
Suitable for Mobile Device?

### ISSUE THREAD

**Issue by InternetMaster1** [zhijieW94/ETNet#2]
Congrats on the amazing advancements on Style Transfer tech.

1) Can this run on a mobile device? Specifically Android

2) What would be the kind of performance we would see vis-a-vis https://www.tensorflow.org/lite/models/style_transfer/overview?

3) I tried the linked Google library, but the final output has too many distortions. If I give a face as content image, the style transfer output comes with too many wrinkles. How would ETNet compare?

**Comment by zhijieW94** [comment]
Hi, thanks for your interests in our paper.

First, I would be sorry that we have not tried to run our model on a mobile device. And based on our limited knowledge on this problem (like model compression), it is hard for us to give a specific answer on how to achieve it.

Second, compared to the linked Google library, I guess our ETNet maybe can present more style elements (like salient colors and various textures)? As for me, the linked model seemingly often suffers from instylization issues and fails to capture some dominant style  patterns. However, none of the current style transfer methods can always output visually pleasing results and how to evaluate them is still an open problem.  So I think both the linked library and our ETNet may have their own advantages in terms of stylization ability.
