### ISSUE TITLE
facing TypeError: unhashable type: 'list'     in windows10 environment.

### ISSUE THREAD

**Issue by ruanjiyang** [zhijieW94/ETNet#3]
Dear zhijieW94,

I'm facing TypeError: unhashable type: 'list'     in windows10 environment.

\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'list'

Could you help to check?  thanks so much!

**Comment by zhijieW94** [comment]
Hi ruanjiyang ,

Sorry for my late response.

We have carefully checked our codes to guarantee their successful execution before we released them. And I never encountered such problem. So could it be attributed to wrongly settled environment?

**Comment by SolicTous** [comment]
A have the same problem
Win10 TF_1_15 Keras_3_2

**Comment by SolicTous** [comment]
Solved,
1) **use TensorFlow 1.12 and keras 2.0.0**
Older TF don't have random, and new like 1.15 just does not work.

2) t7 = torchfile.load(t7_file, force_8bytes_long=True) c**hange  False to True**,
3) and if you have got error with **xrange** change it to range
